server/migrations/20230330224641_initial_tables.js

- add "dropTable" for "users_favorites"

drop users_favorites tables

---

client/src/App.js
client/src/components/ErrorElement.js
client/src/pages/CreateExperiencePage.js
client/src/pages/CreateListingPage.js
client/src/pages/CreateTeamPage.js
client/src/pages/FavoritesPage.js
client/src/pages/HomePage.js
client/src/pages/ListingDetailsPage.js
client/src/pages/ListingExperiencesPage.js
client/src/pages/LoginPage.js
client/src/pages/SignUpPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserPage.js
client/src/pages/UserSettingsPage.js

- create the "pages" for the app
- apply the pages to the router

Organize routes

---

client/src/pages/HomePage.js
server/controllers/usersController.js
server/dbConfig.js
server/models/User.js
server/routes/users.js

This PR's purpose is to simply test a simple knex query on our database:
- Create getAllUsers controller function
- Create getAllUsers model method
- Fetch "/api/users" from homepage
- Display the data

Get all users - TEST

---

client/src/pages/HomePage.js
server/controllers/usersController.js
server/models/User.js
server/routes/users.js

- define model and controller to fetch a single user object from database
Without a UI, to test:
- run Postman or Insomniac
- create a GET request for http://localhost:5000/api/users/:userId

Get single user

---

server/controllers/usersController.js
server/models/User.js
server/routes/users.js

- define model and controller to fetch a user's favorites listings from database
Without a UI, to test:
- run Postman or Insomniac
- create a GET request for http://localhost:5000/api/users/:userId/favorites
Example Response:

Get user favorites

---

client/src/components/AuthedPageContainer.js
client/src/components/AuthedPageTitle.js
client/src/components/Footer.js
client/src/components/Layout.js
client/src/components/Navbar.js
client/src/components/ScrollableList.js
client/src/pages/UserPage.js

This PR:
- adds UI for page UserPage
- adds reusable components AuthedPageContainer, AuthedPageTitle, and ScrollableList
- makes adjustments/css updates for the navbar and footer
- add mobile media query

User page UI

---

server/app.js
server/controllers/usersController.js
server/models/User.js

This PR:
- refactors and cleans up the express handler
- applies the middleware to the controllers
- reformats database error messages

Server error handling refactor

---

client/src/components/AuthFormButton.js
client/src/components/AuthFormField.js
client/src/components/AuthFormRedirect.js
client/src/pages/LoginPage.js
client/src/pages/SignUpPage.js

- modularize form fields for login and signup pages
- modularize buttons
- modularize bottom redirect container
- small changes to margins to maintain consistency

Login signup refactor

---

server/controllers/usersController.js
server/models/User.js
server/routes/users.js

- retrieve user teammates
- build controller, model and knex query
Sample Response:

Get user teammates

---

server/models/User.js

thanks schaeffer

---

client/src/components/AddFavorite.js
client/src/components/AuthedPageContainer.js
client/src/components/DropdownMenuButton.js
client/src/components/FavoriteButton.js
client/src/components/ScrollableList.js
client/src/pages/FavoritesPage.js

Pull Request:
- Adds UI for the page showing the user's favorite job listings
- Adds a height prop to ScrollableList component
- Adds SVG placeholders for future functionality (star on left, circle with three dots on right)
Features/Functionality to be added:
- NavLinks for Company name and possibly job title
- Tab filters/sorting
- Clicking the star on a job listing will add/remove it from favorites
- Dropdown/Hamburger menu when clicking the circle with three dots

User favorites

---

client/src/components/AuthFormButton.js
client/src/components/AuthFormField.js
client/src/components/FormField.js
client/src/pages/LoginPage.js
client/src/pages/SignUpPage.js
client/src/pages/UserSettingsPage.js

This PR:
- adds UI for UserSettingsPage
- adds media query for page

User settings UI

---

server/controllers/usersController.js
server/models/User.js

This PR add checks to controllers, primarily to check if the models return any relevant data.
If they do not, the controllers will now respond accordingly.

Add checks to controllers

---

client/src/App.js
client/src/components/NullInfo.js
client/src/components/ScrollableList.js
client/src/components/UserInfo.js
client/src/pages/UserPage.js
client/src/utils/formatJoinDate.js
package-lock.json

This PR:
- adds loader for client browser router UserPage path
- funnels user, teams, and teammates data to UserPage
- adds NullInfo component for missing user info
- adds UserInfo component that conditionally displays email

User profile to backend

---

client/src/pages/SignUpPage.js

This PR:
- ties signup to backend to allow users to create user object

tie signup to backend to create user

---

client/src/components/NavDropdownButton.js
client/src/components/NavDropdownList.js
client/src/components/Navbar.js

This PR adds NavDropdownList component which will be used to navigate to various pages of app.
Can be seen at top-right corner of screen-cap:

Navbar dropdown menu

---

client/src/components/NavDropdownList.js
client/src/pages/FavoritesPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserPage.js
client/src/pages/UserSettingsPage.js

- add links and logout functionality to hamburger menu
- throw redirects in protected pages

implement hamburger links and add redirects to protected pages

---

client/src/App.js
client/src/pages/TeamsPage.js
server/controllers/teamsController.js
server/models/Team.js
server/routes/teams.js

Pull Request
- Adds get all teams to models, controllers, and routes
- Creates a basic render of the data on the teams page

Get all teams

---

client/src/App.js
client/src/pages/TeamPage.js
client/src/pages/TeamsPage.js
server/controllers/teamsController.js
server/models/Team.js
server/routes/teams.js

Pull Request
- Adds get single team to models, controllers, and routes
- Creates a simple render of the data on the team page. Also basic navlinks to teams page.

GET single team

---

client/src/App.js
client/src/components/AuthedLayout.js
client/src/components/ProtectedLayout.js
client/src/pages/FavoritesPage.js
client/src/pages/HomePage.js
client/src/pages/TeamPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserPage.js
client/src/pages/UserSettingsPage.js

This PR:
- removes all redirects and authedUser checks from pages that require authorization
- moves this logic into the previously defined Layout component
- renames Layout component to AuthedLayout for clarity

Protected routes

---

server/controllers/teamsController.js
server/models/Team.js
server/routes/teams.js

This PR adds route, controller, and model for getAllTeammates for `teams/:teamId` page

Team members get for Team Page

---

server/controllers/teamsController.js
server/models/Team.js
server/routes/teams.js

This PR adds route, controller, and model to "get" all of a team's listings

Team Listings GET

---

.gitignore
package-lock.json
package.json
server/app.js
server/package-lock.json
server/package.json

This PR sets up our app for production.

Production staging

---

client/src/components/ScrollableList.js
client/src/components/SortByDropdown.js
client/src/pages/TeamPage.js

This PR:
- adds UI for TeamPage (singular)
- uses mockData to fill in different sections on page
- fixes bug with SortByDropdown click logic
- adds (non-functional) SortByDropdown to Teams Listings section
- adds proper media queries for mobile (screen-cap below)

Team page UI

---

client/src/components/CreateTeamButton.js
client/src/pages/CreateTeamPage.js
client/src/pages/TeamsPage.js

This PR:
- adds CreateTeamButton in TeamsPage (navigates to CreateTeamPage)
- adds UI for CreateTeamPage

Create team page UI

---

client/public/index.html
server/controllers/teamsController.js
server/models/Team.js
server/routes/teams.js

- Adds ability to change team member status
- includes a list of "approved statuses" that the model checks against
- changes title of our application

Patch users teams

---

server/controllers/teamsController.js
server/models/Team.js
server/routes/teams.js

- deletes team member from team
- includes TODO comments which in the future will check if calling user has permissions to change member status, delete a member, or update a team

Delete users teams

---

client/src/App.js
client/src/pages/TeamPage.js
client/src/pages/TeamSettingsPage.js
client/src/pages/UserSettingsPage.js

This PR:
- adds the TeamSettingsPage page
- adds button in TeamPage to navigate to team settings page
- adds similar ui to create team page

Team settings page UI

---

client/src/App.js
client/src/pages/DeleteTeamPage.js
client/src/pages/TeamSettingsPage.js

This PR:
- adds page and UI for DeleteTeamPage
- uses loader to import team data

Delete team page UI

---

client/src/pages/TeamPage.js

This PR: 
- adds invite form to TeamPage
- adds Team's job field

Add invite job field team page

---

client/src/pages/TeamPage.js
server/models/User.js

- Refines getUserTeammates by omitting teammates that have status "pending" or "requested"

refines getUserTeammates

---

client/src/App.js
client/src/components/Dashboard.js
client/src/components/TeamAdminAuthorization.js
client/src/pages/DeleteTeamPage.js
client/src/pages/FavoritesPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamSettingsPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserPage.js
client/src/pages/UserSettingsPage.js

- moves data manipulation logic from page components to the loaders
- refactors/cleans up TeamPage
- removes some mock listing data for easier code visibility

Move data manipulation to loaders

---

client/src/App.js
client/src/pages/CreateExperiencePage.js
client/src/pages/CreateListingPage.js
client/src/pages/CreateTeamPage.js
client/src/pages/DeleteAccountPage.js
client/src/pages/DeleteTeamPage.js
client/src/pages/FavoritesPage.js
client/src/pages/HomePage.js
client/src/pages/ListingDetailsPage.js
client/src/pages/ListingExperiencesPage.js
client/src/pages/LoginPage.js
client/src/pages/SignUpPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamSettingsPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserPage.js
client/src/pages/UserSettingsPage.js

- Moves loader logic to the pages they belong to
- Changes to the way we export/import pages
- Small adjustments to various loaders

Refactor modularize loaders

---

client/src/App.js
client/src/components/Dashboard.js
client/src/components/Navbar.js
client/src/components/UserAuthorization.js
client/src/pages/DeleteAccountPage.js
client/src/pages/DeleteTeamPage.js
client/src/pages/FavoritesPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamSettingsPage.js
client/src/pages/UserSettingsPage.js

- Adds missing navlinks to team lists in dashboard
- Adds missing navlinks to teammates lists in team page
- Adds links to page titles
- Adds isActive styling to navlinks in navbar
- Adds UserAuthorization to UserFavorites page
- Modifies router to be more modular with UserAuthorization pages
- Modifies UserAuthorization to render Outlet instead of children

Add links to lists

---

client/src/pages/TeamPage.js

- Adds a request to join team button to team page
- Will only show if user is not a member(button will still persist if invited or requested to join)
- Change logic to only show invite friend form if the user is an established member

Request to join team

---

server/controllers/usersController.js
server/models/User.js
server/routes/users.js

- Implements route, controller and model for posting new user favorite

Favorites post

---

client/src/App.js
client/src/components/ScrollableList.js
client/src/pages/CreateListingPage.js
client/src/pages/TeamPage.js

This PR 
- adds CreateListingPage
- adds navigations from Team page to this Page
- adds state to control values in form
- uses title for navigation to previous pages

Create listing page UI

---

client/src/components/Dashboard.js
client/src/components/FavoriteButton.js
client/src/pages/FavoritesPage.js
client/src/pages/TeamPage.js
server/app.js
server/controllers/usersController.js
server/migrations/20230417204904_users_favorites_unique.js
server/models/User.js
server/routes/users.js

- creates route, controller, model for deleting a favorite
- implements migration to add constraint to make users_favorites entries unique
- connects the favorites button to API

Favorites delete

---

server/app.js
server/controllers/listingsController.js
server/models/Listing.js
server/routes/listings.js

Pull Request:
- creates controller, model, and route for getting a single listing by ID

Get single listing by ID

---

client/src/pages/CreateListingPage.js
server/controllers/listingsController.js
server/models/Listing.js
server/routes/listings.js

This PR:
- adds the ability to create a listing for a user's team
- adds route, controller and model for 
- was verified using postman and pgAdmin
- adds proper navigation when "create listing" form is submitted
Below is verification that listing is added to db:
Screen-cap from pgAdmin4:

Create listing post

---

client/src/App.js
client/src/components/FavoriteButton.js
client/src/pages/CreateTeamPage.js
client/src/pages/ListingDetailsPage.js
client/src/pages/TeamPage.js

- Creates UI for ListingDetails Page
- Creates loader for ListingDetailsPage
- Connects data to the UI
- Implements add/delete to favorites functionality
- Creates NavLink from team page to listing page
- Adds missing link in title of CreateTeamPage

Listing details UI

---

server/controllers/listingsController.js
server/models/Listing.js
server/routes/listings.js

Pull Request:
- Adds controller, model, and route for DELETE listing by ID
- Tested with POSTMAN

Delete listing by ID

---

server/controllers/listingsController.js
server/models/Listing.js
server/routes/listings.js

Pull Request:
- Added controllers, models, routes for update listing by id
- Tested with POSTMAN

PATCH listing by ID

---

client/src/App.js
client/src/pages/EditListingPage.js
client/src/pages/ListingDetailsPage.js
server/models/Listing.js

This PR
- adds EditListingPage UI, navigation, and axios patch to backend
- adds conditional edit button to listing details page dependent on whether authed user matches the listing userId
Pictures show that changes made in edit page reflect on listing details page

Edit listing page UI

---

client/src/App.js
client/src/components/ErrorElement.js
client/src/pages/NotFoundPage.js

- Create NotFoundPage to catch all undeclared routes
- Creates ErrorElement to be displayed if errors happen on fetching

Error element

---

client/src/App.js
client/src/pages/DeleteListingPage.js
client/src/pages/EditListingPage.js

This PR: 
- adds DeleteListingPage ui, navigation and axios delete to hit listing delete route
- adds navigation from EditListingPage to DeleteListingPage
- tested multiple delete listings and verified in pgAdmin and in Team Listings UI

Delete listing page UI

---

server/seeds/7_comments_seed.js
server/seeds/data/comments.json

Pull Request:
- Adds seeder data for comments

added seeder data for comments

---

server/app.js
server/controllers/commentsController.js
server/models/Comment.js
server/routes/comments.js

This PR 
- adds model, controller and route for getting a listing's comments 
- adds route to app.js
- creates files for the server functions

add route, controller, model for getListingComments

---

server/controllers/commentsController.js
server/models/Comment.js
server/routes/comments.js

This PR:
- adds route, controller and model for adding comments

add route, controller and model for adding comments

---

client/src/pages/TeamsPage.js
server/models/Team.js

- adds userCount to teams query, filters out "requested" and "invited" statuses
- displays userCount in UI

Add user count to teams query

---

client/src/components/Dashboard.js
client/src/pages/HomePage.js
client/src/utils/shuffleArray.js
server/controllers/teamsController.js
server/models/Team.js
server/routes/teams.js

- Rework of query to recommend to the user some teams based off mutual teammates
- Removes "job field" query implementation, should consider adding a "preferred job field" column to "users"
- Ties the backend to Dashboard UI 
- Leaves comments in the model for future reference and for description of query

Get recommended teams

---

client/src/App.js
client/src/components/TeamMemberAuthorization.js
client/src/pages/CreateListingPage.js
client/src/pages/DeleteListingPage.js
client/src/pages/EditListingPage.js

- Adds more route protections to listing and experience related routes
- Preemptively leaves commented out protection for routes not yet implemented
- TODO: Refactor and reorganize once all routes are created and implemented

Route protections

---

client/package-lock.json
client/package.json
client/src/components/ScrollableList.js
client/src/pages/ListingDetailsPage.js
server/models/Comment.js
server/seeds/data/comments.json
server/utils/auth.js

This PR:
- adds UI for comments
- links to backend
- allows for inline editing comments
- allows users to add new comments 
- allows users to delete comments they created

Comments UI

---

client/src/components/CommentsSection.js
client/src/pages/ListingDetailsPage.js

This PR refactors the "comments" section into its own component

Comments refactor

---

server/migrations/20230421224448_index_username.js

- Adds indexing to username
- This is in preparation for API rework, hope to greatly simplify User API

add index to user username

---

client/src/pages/CreateListingPage.js
client/src/pages/DeleteListingPage.js
client/src/pages/DeleteTeamPage.js
client/src/pages/EditListingPage.js
client/src/pages/ListingDetailsPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamSettingsPage.js
server/controllers/teamsController.js
server/routes/teams.js

- Removes excess routes and bundles extra information into getSingleTeam
- Applies necessary changes to page components and loaders

Teams API Rework

---

client/src/pages/HomePage.js
client/src/pages/TeamPage.js
server/controllers/sessionController.js

- Hides listings from TeamPage if user is not a member of team
- Hides Requests tab from TeamPage if user is not a member of team
- Hides Requests tab data from TeamPage if user is not a member of team
- NOTES: When ScrollableList is refactored, changes will be made to the blurred div
- NOTES: Combines tickets 105 and 119 in Jira
In team:
Not in team:

Hide listings and requests

---

client/src/components/AcceptButton.js
client/src/components/DenyButton.js
client/src/components/ScrollableList.js
client/src/pages/TeamPage.js
client/src/pages/UserPage.js

This PR removes unnecessary z-indexes

Fix unnecessary z index

---

server/controllers/experiencesController.js
server/models/Experience.js
server/routes/experiences.js

Pull Request:
- creates controllers, models, routes for getting a single experience

GET single experience

---

client/src/components/Dashboard.js
client/src/pages/TeamPage.js

- Adds ability to accept/deny requests on team page

Accept deny requests

---

server/controllers/experiencesController.js
server/models/Experience.js
server/routes/experiences.js

This PR adds delete experience route, controller and model

adds delete experience route, controller and model

---

server/controllers/listingsController.js
server/models/Listing.js

- Implements model to getListingExperiences
- Applies model to getListing controller

Get experiences

---

server/controllers/experiencesController.js
server/models/Experience.js
server/routes/experiences.js

Pull Request:
- Adds to controller, models, routes for creating an experience

POST experience

---

client/src/pages/ListingExperiencesPage.js

This PR: 
- adds inline editing for authorized user experience

Edit experience UI

---

client/src/components/ListingTabs.js
client/src/components/ListingTeammatesSection.js
client/src/pages/ListingDetailsPage.js
client/src/pages/ListingExperiencesPage.js

- Modularizes Teammates for ListingExperiences and ListingDetails pages
- Modularizes Tabs for ListingExperiences and ListingDetails pages

Teammates + Tabs refactor

---

client/src/App.js
client/src/pages/CreateExperiencePage.js
client/src/pages/ListingExperiencesPage.js
server/models/Listing.js

Pull Request:
- Adds UI for creating a new experience
- Adds navigation to the create experience page to the experiences scrollable list
- Orders the experiences by most recently created. Added to backend.

Create experience UI

---

client/src/components/AuthedPageTitle.js
client/src/components/Dashboard.js
client/src/pages/CreateExperiencePage.js
client/src/pages/CreateListingPage.js
client/src/pages/CreateTeamPage.js
client/src/pages/DeleteAccountPage.js
client/src/pages/DeleteListingPage.js
client/src/pages/DeleteTeamPage.js
client/src/pages/EditListingPage.js
client/src/pages/FavoritesPage.js
client/src/pages/ListingDetailsPage.js
client/src/pages/ListingExperiencesPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamSettingsPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserPage.js
client/src/pages/UserSettingsPage.js

Pull Request:
- Refactors page titles to be a component

Page Title Refactor

---

client/src/components/CommentsSection.js
client/src/components/Dashboard.js
client/src/components/ListingTeammatesSection.js
client/src/components/ScrollableList.js
client/src/pages/FavoritesPage.js
client/src/pages/ListingDetailsPage.js
client/src/pages/ListingExperiencesPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserPage.js

This PR:
- removes sizing and ref  props from ScrollableList
- adds these outside of the component

Scrollable list refactor

---

client/src/components/Dashboard.js
client/src/pages/FavoritesPage.js
client/src/pages/ListingDetailsPage.js
client/src/pages/ListingExperiencesPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamSettingsPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserPage.js
client/src/pages/UserSettingsPage.js
server/routes/experiences.js

This PR removes unused imports and deletes unnecessary spacing

remove unused imports and delete unnecessary spacing

---

client/src/components/ListingDetails.js
client/src/pages/ListingDetailsPage.js

- Makes ListingDetails into its own components
- Minor CSS changes

Refactor listing details page

---

client/src/components/Experience.js
client/src/components/ListingExperiences.js
client/src/pages/ListingExperiencesPage.js

- Creates ListingExperiences and Experience components
- Refactors ListingExperiencesPage

Refactor listing experiences page

---

client/src/components/InviteTeammateForm.js
client/src/components/RequestToJoinForm.js
client/src/components/TeamListings.js
client/src/components/TeammatesAndRequests.js
client/src/pages/TeamPage.js

- Refactors TeamPage
- Creates TeamListings, InviteTeamForm, RequestToJoinForm, and TeammatesAndRequests components

Refactor team page

---

client/src/components/AllTeams.js
client/src/components/UserTeams.js
client/src/pages/TeamsPage.js

- Refactors TeamsPage
- Creates AllTeams and UserTeams components

Refactor teams page

---

client/src/components/Dashboard.js
client/src/components/RecentActivity.js
client/src/pages/HomePage.js
server/controllers/sessionController.js
server/models/User.js

- Creates a model that returns recent activity for session user
- Model returns activity for comments, experiences and listings
- Loads in the data to HomePage loader and Dashboard component
- Creates a new component, RecentActivity, that organizes and displays each recent activity
- Adds navigation links to content in RecentActivity
- Applies the RecentActivity component to Dashboard component

Recent activity

---

server/routes/experiences.js
server/routes/listings.js
server/routes/teams.js
server/utils/validation.js

- Validates Team(Create and Update)
- Validates Listing(Create and Update)
- Validates Experience(Create)

Validate teams listings experiences

---

client/src/pages/CreateTeamPage.js
client/src/pages/TeamSettingsPage.js

- Applies searchable job fields to both CreateTeamPage and TeamSettingsPage
Selecting:
Once selected:
Cleared:

Job fields teams

---

client/src/components/AuthFormButton.js
client/src/components/AuthFormRedirect.js
client/src/components/Footer.js
client/src/pages/LoginPage.js

change login to figma hi-fidelity design

---

client/src/pages/LoginPage.js
client/src/pages/SignUpPage.js

Sign up UI 2.0

---

server/migrations/20230508233442_experiences-questions.js

- Creates "experiences_questions" table for experience interview questions

Experiences questions table

---

server/migrations/20230509012223_experiences_links.js

- Creates migration/table for "experiences_links"

Experiences links table

---

server/app.js
server/controllers/experiencesController.js
server/controllers/questionsController.js
server/models/Experience.js
server/models/Question.js
server/routes/experiences.js
server/routes/questions.js

- Implements models for adding, updating, deleting, and getting all questions (getting all questions applied to experience model/controller)
- Creates router and controller for Question model

Experiences questions backend

---

server/app.js
server/controllers/experiencesController.js
server/controllers/linksController.js
server/models/Experience.js
server/models/Link.js
server/routes/links.js

- Creates model to get all experience links and applies to experience controller
- Creates models, controllers and routes for Links (POST and DELETE, excluding PATCH -- seems unnecessary for links)
Incoming experience will now look like this:
POST link response:
DELETE link response:

Experiences links backend

---

client/src/components/AuthedLayout.js
client/src/components/AuthedPageContainer.js
client/src/components/AuthedPageTitle.js
client/src/components/Footer.js
client/src/components/Logo.js
client/src/components/LogoSmall.js
client/src/components/NavDropdownList.js
client/src/components/Navbar.js
client/src/components/UnauthedLayout.js
client/src/pages/TeamPage.js

This PR:
- adds changes/ removes restrictions in AuthPageContainer AuthPageTitle
- adjusts z-index to accommodate new sticky "link bar" (AuthPageTitle)
- adds ScrollRestoration to layouts
- minor adjustments to Navbar and Footer

Reusable components refactor for Dashboard and UserProfile

---

client/src/components/AllTeams.js
client/src/components/FilterButton.js
client/src/components/FilterTeamsModal.js
client/src/pages/TeamsPage.js

- renames setIsFilterModalShowing prop to handleFilterModal
- cleans up page css

minor adjustments

---

client/src/components/CreateListingModal.js
client/src/components/CreateTeamButton.js
client/src/components/CreateTeamModal.js
client/src/components/DeleteAccountButton.js
client/src/components/DeleteAccountModal.js
client/src/components/ModalLayout.js
client/src/pages/TeamsPage.js
client/src/pages/UserSettingsPage.js

- Refactors modal layout into ModalLayout
- Lifts rendering of basic modals to the pages they exist on
- CSS adjustments

Modal refactor

---

client/src/components/AllTeams.js
client/src/components/SortByDropdown.js

- Adjust mobile and desktop layouts for filtering the TeamsPage

Teams Filter UI Adjustments

---

client/src/components/AllTeams.js
client/src/components/FilterListingsModal.js
client/src/components/SearchInput.js
client/src/components/SortByDropdown.js
client/src/components/TeamListings.js
client/src/pages/FavoritesPage.js
client/src/utils/sortListings.js

- Updates UI for favorites page
- Creates reusable SearchInput component
- Creates mobile modal to filter listings
- Creates sortListings utility function

Favorites 2.0

---

client/src/components/DeleteExperienceModal.js
client/src/components/ExperienceDetails.js
client/src/components/ListingExperiences.js
client/src/pages/ListingExperiencesPage.js
client/src/pages/ListingPage.js

- Implements rough draft of ExperienceDetails component
- TODO: Discuss listing tabs and handling multiple buttons
- TODO: Discuss inline editing for listing and experience components
- NOTE: Left some unused code for future reference regarding inline editing

Experience details 2.0

---

client/package-lock.json
client/package.json
client/src/components/AuthedLayout.js
client/src/pages/LoginPage.js

- Implements React Top Loading Bar in place of LoadingSpinner for authed pages
- Adds navigate to login handler

Loading rework 2.0

---

client/src/components/ExperienceDetails.js
client/src/components/ListingDetails.js
client/src/components/UserInterests.js
client/src/components/UserReadMe.js
client/src/components/UserTeammatesList.js
client/src/components/UserTeamsList.js
client/src/pages/TeamPage.js

- Updates descriptions css for:
- User readme
- Team credo
- Experience content
- Listing company details and job description
- Fixes overflow bug for collapsible UserTeamsList and UserTeammatesList in UserPage

Quill view details update

---

client/src/layouts/UserSettingsLayout.js
client/src/pages/UserAppearanceSettingsPage.js
client/src/pages/UserPhotoSettingsPage.js

- Implements UI for UserPhotoSettingsPage
- Implements functionality to change default avatar photo
- Adds conditionals to check for future user uploaded photo
- Utilizes authedUser and setAuthedUser to render changed avatar throughout the app
- TODO: Add react-hot-toast to display popup success/error on updating avatar
- TODO: Implement upload profile picture
Desktop:
Tablet:
Mobile:

User Photo Settings UI

---

client/src/pages/TeamPhotoSettingsPage.js
client/src/pages/UserPhotoSettingsPage.js
client/src/utils/teamAvatars.js
server/controllers/commentsController.js
server/controllers/linksController.js
server/controllers/listingsController.js
server/controllers/questionsController.js
server/controllers/sessionController.js
server/controllers/teamsController.js
server/routes/session.js
server/routes/teams.js

- Implements UI for TeamPhotoSettingsPage
- Adds functionality to change team avatar
- Creates routes and controllers to update team photo and avatar
- Creates routes and controllers to update user photo and avatar
- Adds loader revalidation to TeamPhotoSettingsPage and UserPhotoSettingsPage
- Updates a few returned status codes in the server
Desktop:
Tablet:
Mobile:

Team avatar UI

---

client/src/components/Dashboard.js
client/src/index.css
client/src/layouts/TeamSettingsLayout.js
client/src/layouts/UserSettingsLayout.js
client/src/pages/FavoritesPage.js
client/src/pages/ListingPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserPage.js
client/src/utils/dateFormatters.js
client/src/utils/sortListings.js
server/models/User.js

This PR:
- updates the FAVORITES Page list UI
- implements use of html table instead of ul
- adds more information about each listing (table columns)
- adds new sorting UI and removes sortBy dropdown
- removes padding changes for larger media queries app-wide

Update listings list

---

client/src/components/UserInfo.js
client/src/index.css
client/tailwind.config.js

- Updates UI to UserInfo in UserPage

User info update

---

client/src/components/TeamListings.js
server/migrations/20230606034336_listing_salary.js

- Creates migration to handle listing salary
- Adds "salaryAmount" to listings table
- Adds "salaryFrequency" to listings table 
- Checks "salaryFrequency" to only allow certain values

Listing salary backend

---

client/src/components/Dashboard.js
client/src/components/RecentActivity.js
server/models/User.js

This PR: 
- updates UI for RecentAvtivity component 
- updates href for experience links 
- adds "query_id" to getRecentActivity user model to access experience id

Update recent activity list

---

client/src/components/AllTeams.js
client/src/components/TeamListings.js
client/src/pages/FavoritesPage.js
client/src/utils/sortListings.js
client/src/utils/sortTeams.js

This PR
- updates team listings UI
- adds new salary data to listing
- implements new sort ui

Update team listings

---

client/src/components/InviteTeammateForm.js
client/src/components/UserInfo.js
client/src/pages/ListingPage.js
client/src/pages/TeamMembersSettingsPage.js

- Creates UI for TeamSettingsMembersPage
- Lists are responsive (mobile: 1 column, desktop: minimum 2 columns, maximum 3 columns)
- Adds functionality to:
- Promote "member" to "admin"
- Demote "admin" to "member"
- Remove existing "member" from team
- Invite users to join team
- Remove already sent out invites
- Accept requests to join
- Deny requests to join
- Adds creator's username to ListingPage
- NavLink to direct to the user's profile
- Only visible on desktop, mobile is too cluttered 
Desktop:
Mobile:
Listing Page:

Manage team members

---

client/src/components/UserTeamsList.js

- Updates UserTeamList UI in UserPage

Update UserTeamsList UI

---

server/controllers/teamsController.js
server/routes/teams.js

Pull Request:
- Adds to controllers and routes for uploading/removing team photo

backend for updating and removing team photo

---

client/src/pages/TeamPhotoSettingsPage.js
server/controllers/teamsController.js

Pull Request:
- Adds front end functionality for uploading/removing photo
- Minor fix to backend error
- id > teamId

added frontend for team photo. minor fix to backend

---

client/src/pages/TeamPhotoSettingsPage.js
server/controllers/teamsController.js
server/routes/teams.js

Team Photo Uploads

---

client/src/App.js
client/src/context/AuthContext.js
client/src/pages/ConfirmAccountPage.js
client/src/pages/LoginPage.js
client/src/pages/SignUpPage.js
server/app.js
server/controllers/sessionController.js
server/controllers/usersController.js
server/migrations/20230612211412_user_account_confirmation.js
server/models/User.js
server/package-lock.json
server/package.json
server/routes/session.js
server/utils/nodemailer.config.js

Pull Request:
- Sets up account email verification through nodemailer package
- Connects frontend and adds basic, unstyled page

Create account confirmation

---

client/src/index.css
client/src/pages/ConfirmAccountPage.js
client/src/pages/SignUpPage.js

This PR: 
- adds UI for account confirmation page
- adds color variable to global css
- changes sign up page to not render form on success

Account confirmation page UI

---

client/src/App.js
client/src/pages/ForgotPasswordPage.js
client/src/pages/LoginPage.js
client/src/pages/ResetPasswordPage.js
server/app.js
server/controllers/usersController.js
server/migrations/20230613201208_reset_password.js
server/models/User.js
server/routes/users.js
server/utils/nodemailer.config.js

This PR:
- adds migration for a user reset password token
- adds email send for forgotten password in nodemailer config
- adds route, controller and model for sending email
- adds UI for ForgotPasswordPage
- adds route and controller for reset password
- adds UI for ResetPasswordPage

Add forgot password

---

client/src/App.js
client/src/components/Footer.js
client/src/components/NavDropdownList.js
client/src/context/AuthContext.js
client/src/index.css
client/src/layouts/SwitchLayout.js
client/src/pages/ConfirmAccountPage.js
client/src/pages/ContactUsPage.js
server/app.js
server/controllers/usersController.js
server/routes/users.js
server/seeds/data/users.js
server/utils/nodemailer.config.js

This PR:
- creates route and controller for Contact page
- adds function to nodemailer config to send message to designated teamapp email
- adds the ContactUsPage.js and UI for frontend 
- adds SwitchLayout
- this allows us to use either AuthedLayout or UnauthedLayout for pages like ContactUsPage
- adds account_status to users seed file

Contact us Page

---

client/src/index.css
server/controllers/commentsController.js
server/controllers/experiencesController.js
server/controllers/linksController.js
server/controllers/listingsController.js
server/controllers/questionsController.js
server/controllers/sessionController.js
server/controllers/teamsController.js
server/controllers/usersController.js
server/models/Comment.js
server/models/Experience.js
server/models/Link.js
server/models/Listing.js
server/models/Question.js
server/models/Team.js
server/models/User.js
server/routes/users.js

- Models:
- console.errors descriptive developer errors from knex
- throws user friendly error messages for use in UI
- Controllers:
- adds more errors
- opts to use `res.status().json()` inside controller `try` statements instead of `next(err)` -- we are effectively achieving the same thing but with less lines of code

Error handling cleanup backend

---

client/src/components/ListingComments.js
client/src/components/TeamsSideList.js
server/controllers/sessionController.js

- Revert back to original getSession implementation

backend error handling fast follow

---

client/src/components/CreateExperienceModal.js
client/src/components/CreateListingModal.js
client/src/components/CreateTeamModal.js

- Implements minor updates to:
- CreateTeamModal
- CreateListingModal
- CreateExperienceModal
- Removes UPPERCASE labeling and heading
- Changes background to `bg-secondary` for desktop view

Create modal UI update

---

client/src/components/ListingExperiences.js

- Updates ListingExperience to closer match our overall design theme

update listing experiences ui

---

client/src/components/AllTeams.js
client/src/components/CreateTeamModal.js
client/src/components/Dashboard.js
client/src/components/ExperienceDetails.js
client/src/components/NullInfo.js
client/src/components/TeamListings.js
client/src/components/TeamsSideList.js
client/src/components/UserSettingsInterests.js
client/src/components/UserTeamsList.js
client/src/pages/FavoritesPage.js
client/src/pages/TeamMembersSettingsPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserAppearanceSettingsPage.js

This PR:
- adds prop to NullInfo component add a customized message for empty lists/information
- adds messages to pages and components using NullInfo component
- updates UI for the theme selection

Null info theme UI

---

client/src/components/DeleteAccountModal.js
client/src/context/AuthContext.js
client/src/layouts/UserSettingsLayout.js
client/src/pages/FavoritesPage.js
client/src/pages/HomePage.js
client/src/pages/ListingPage.js
client/src/pages/TeamPage.js
client/src/pages/TeamsPage.js
client/src/pages/UserAppearanceSettingsPage.js
client/src/pages/UserPhotoSettingsPage.js
client/src/pages/UserProfileSettingsPage.js
server/controllers/sessionController.js
server/controllers/usersController.js
server/routes/session.js
server/routes/users.js

- Restructures user and session routers
- Moves controllers
- Adjusts axios calls

Restructure user session routes

---

client/src/components/AllTeams.js
client/src/components/FavoriteButton.js
client/src/components/TeamListings.js
client/src/pages/FavoritesPage.js
client/src/pages/TeamPage.js
server/controllers/teamsController.js
server/controllers/usersController.js
server/models/Team.js
server/models/User.js

- Creates server side querying for 
- Favorites
- TeamListings

Favorites team listings query

---

client/src/components/LogoSmall.tsx
client/src/pages/ConfirmAccountPage.tsx

- Implements typescript for ConfirmAccountPage

finish Confirm Account Page

---

client/src/components/AuthedPageTitle.tsx
client/src/components/FavoriteButton.tsx
client/src/pages/FavoritesPage.tsx
client/src/utils/dateFormatters.ts
client/src/utils/formatSalary.ts

- Adds typescript to FavoritesPage component tree

Ts favorites page

---

client/src/pages/ForgotPasswordPage.tsx

- Implement typescript for ForgetPasswordPage

ForgotPasswordPage

---

client/src/components/Dashboard.tsx
client/src/components/RecentActivity.tsx
client/src/pages/HomePage.tsx

- Implements typescript for HomePage component tree

finish HomePage component tree

---

client/src/components/CreateExperienceModal.tsx
client/src/components/DeleteExperienceModal.tsx
client/src/components/DeleteListingModal.tsx
client/src/components/ExperienceDetails.tsx
client/src/components/ListingComments.tsx
client/src/components/ListingDetails.tsx
client/src/components/ListingExperiences.tsx
client/src/components/ListingTabs.tsx
client/src/layouts/DeleteModalLayout.tsx
client/src/layouts/ModalLayout.tsx
client/src/pages/ListingPage.tsx
client/src/utils/trimUrl.ts
client/type-definitions.d.ts

- Implements typescript for ListingPage component tree

Ts listing page

---

client/src/components/AuthFormRedirect.tsx
client/src/context/AuthContext.tsx
client/src/pages/LoginPage.tsx

- Implements typescript for LoginPage component tree

Ts login page

---

client/src/pages/NotFoundPage.tsx
client/src/pages/ResetPasswordPage.tsx

- Implements typescript for NotFound and ResetPassword pages component trees

NotFound and ResetPassword pages

---

client/src/context/AuthContext.tsx
client/src/pages/SignUpPage.tsx

- Implements typescript for SignUpPage component tree
- Updates AuthContext signup and googleSignup

SignUpPage and AuthContext update

---

client/src/components/InviteTeammateForm.tsx
client/src/pages/TeamMembersSettingsPage.tsx
client/type-definitions.d.ts

- Implement typescript for TeamMembersSettingsPage component tree

Ts team members settings page

---

client/src/components/BlurredListings.tsx
client/src/components/CreateListingModal.tsx
client/src/components/RequestToJoinForm.tsx
client/src/components/TeamListings.tsx
client/src/components/Teammates.tsx
client/src/pages/TeamPage.tsx
client/type-definitions.d.ts

- Implements typescript for TeamPage component tree

Ts team page

---

client/src/layouts/TeamSettingsLayout.tsx
client/src/layouts/UserSettingsLayout.tsx
client/src/pages/TeamPhotoSettingsPage.tsx
client/src/utils/teamAvatars.ts

- Implements typescript for TeamPhotoSettingsPage component tree, and TeamSettingsLayout and UserSettingsLayout

Ts team photo settings page

---

client/src/components/CreateExperienceModal.tsx
client/src/components/CreateTeamModal.tsx
client/src/components/DeleteTeamModal.tsx
client/src/components/UserSettingsInterests.js
client/src/pages/TeamPrivacySettingsPage.tsx
client/src/pages/TeamProfileSettingsPage.tsx

- Implements typescript for:
- TeamPrivacySettingsPage
- DeleteTeamModal
- TeamProfileSettingsPage
- Adjusts html for team job field change

Ts team profile settings team privacy settings

---

client/src/components/Dashboard.tsx
client/src/components/FavoriteButton.tsx
client/src/components/FilterByInterests.tsx
client/src/components/UserInfo.tsx
client/src/components/UserInterests.tsx
client/src/components/UserReadMe.tsx
client/src/components/UserSocials.tsx
client/src/components/UserTeammatesList.tsx
client/src/components/UserTeamsList.tsx
client/src/pages/FavoritesPage.tsx
client/src/pages/TeamsPage.tsx
client/src/pages/UserPage.tsx
client/type-definitions.d.ts

- Implement typescript for UserPage component tree
- Clean up UserType

Ts user page

---

server/controllers/authController.ts
server/controllers/commentsController.ts
server/controllers/experiencesController.ts
server/controllers/linksController.ts
server/controllers/listingsController.ts
server/controllers/questionsController.ts
server/controllers/teamsController.ts
server/controllers/usersController.ts
server/models/Comment.ts
server/models/Experience.ts
server/models/Link.ts
server/models/Listing.ts
server/models/Question.ts
server/models/Team.ts
server/models/User.ts
server/routes/auth.ts
server/routes/comments.ts
server/routes/experiences.ts
server/routes/links.ts
server/routes/listings.ts
server/routes/questions.ts
server/routes/teams.ts
server/routes/users.ts
server/types/index.d.ts
server/utils/validation.ts

Types out server controllers and models

Typescript server 2

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/AppItem.tsx
client/src/components/AppsColumn.tsx
client/src/components/Navbar.tsx
client/src/components/StrictModeDroppable.tsx
client/src/layouts/AppsLayout.tsx
client/src/pages/AppsBoardPage.tsx

- Installs dependencies for `react-beautiful-dnd`
- Sets up new page for application board
- Creates lowfi board using mock data

My apps UI

---

client/src/App.tsx
client/src/components/AppItem.tsx
client/src/components/AppsColumn.tsx
client/src/layouts/AppsLayout.tsx
client/src/pages/AppsBoardPage.tsx
client/type-definitions.d.ts
server/controllers/usersController.ts
server/models/User.ts
server/types/index.d.ts

- Links user applications and statuses to kanban board

Get app statuses

---

client/src/components/AppItem.tsx
client/src/pages/AppsBoardPage.tsx
server/app.ts
server/controllers/appStatusesController.ts
server/models/AppStatuses.ts
server/models/User.ts
server/routes/appStatuses.ts

- Renames frontend column IDs
- Creates router for appStatuses
- Creates route, model and controller to update user app statuses
- Applies endpoint to kanban board

Reorder board columns

---

client/src/components/DeleteAppStatusModal.tsx
client/src/pages/AppsBoardPage.tsx

- Ability to move applications within same column or to different column

Move applications

---

client/src/components/AppsColumn.tsx
client/src/components/CreateListingModal.tsx
client/src/components/DeleteAppStatusModal.tsx
client/src/components/TeamListings.tsx
client/src/pages/AppsBoardPage.tsx
client/src/pages/TeamPage.tsx
server/models/Listing.ts

- Adds ability to create application on MyApps board page
- Removes ability to create application/listing on Team page
- Adjusts relevant models
- Minor code cleanup

Create application board page

---

client/src/App.tsx
client/src/components/Dashboard.tsx
client/src/components/Logo.tsx
client/src/components/NavDropdownList.tsx
client/src/components/NavNotifsDropdown.tsx
client/src/components/NavUserDropdown.tsx
client/src/components/Navbar.tsx
client/src/layouts/AuthedLayout.tsx
client/src/layouts/SwitchLayout.tsx
client/src/pages/ContactUsPage.tsx
client/src/pages/ForgotPasswordPage.tsx
client/src/pages/HomePage.tsx
client/src/pages/LoginPage.tsx
client/src/pages/ResetPasswordPage.tsx
client/src/pages/SignUpPage.tsx

This PR:
- removes "Notifications" section from Dashboard
- adds Notifications to NavBar
- adds animations to Notifications
https://github.com/SVG-Productions/teamUpp/assets/100656411/05e3cfbe-c527-4a73-bcef-2327d795ed47

Move notifications to navbar

---

client/src/components/LogoSmall.tsx
client/src/components/NavNotifsDropdown.tsx
client/src/components/NavUserDropdown.tsx
client/src/components/Navbar.tsx

This PR:
- adds animation to the NavUserDropdown component
- adds animation to other links in Navbar component
https://github.com/SVG-Productions/teamUpp/assets/100656411/fb2a6b06-9e2e-419e-b1db-9d93b27b0830

Add animation user dropdown

---

client/src/components/AppItem.tsx
client/src/components/AppsColumn.tsx
client/src/components/BoardAppDetailsModal.tsx
client/src/components/CreateListingModal.tsx
client/src/components/DeleteAppStatusModal.tsx
client/src/components/DeleteListingModal.tsx
client/src/components/LoadingSpinner.tsx
client/src/components/NavNotifsDropdown.tsx
client/src/pages/AppsBoardPage.tsx
client/src/pages/ListingPage.tsx
server/models/Listing.ts

- TODO: Fix bugs, code cleanup, and apply useCallback/useMemo

Board app details modal

---

client/src/App.tsx
client/src/components/AppItem.tsx
client/src/components/AppsColumn.tsx
client/src/components/BoardAppDetailsModal.tsx
client/src/components/CreateBoardAppModal.tsx
client/src/components/DeleteAppStatusModal.tsx
client/src/context/BoardContext.tsx
client/src/pages/AppsBoardPage.tsx
server/models/User.ts
server/types/index.d.ts

- Creates context for apps board
- Fixes BoardAppDetailsModal state issues
- Fixes setState for app status within BoardAppDetailsModal bug
- Adds minor render performance enhancements via memo() and useMemo()

Board page cleanup

---

client/src/components/BoardAppDetailsModal.tsx

- Makes setState a bit more readable
- Persists status change to database

Persist board app details modal status changes

---

client/src/components/ExperienceDetails.tsx
client/src/components/ListingTabs.tsx
client/src/index.css
client/tailwind.config.js

This PR: 
- adds animation to ExperienceDetails component 
- adds animation to the ListingTabs component 
- adds tailwind variable
https://github.com/SVG-Productions/teamUpp/assets/100656411/21065b8d-a175-440e-96d6-2f504e63b17c

Experience details animation

---

client/src/components/AppItem.tsx
client/src/components/AppsColumn.tsx
client/src/index.css

- Updates styling for:
- AppItem
- AppColumn
- bg-tertiary color variable
Before:
After:

App item css

---

client/src/components/BoardAppDetailsModal.tsx
client/src/pages/AppsBoardPage.tsx

- Adds mobile styling to app details modal

App details modal mobile

---

client/src/components/BoardAppDescription.tsx
client/src/components/BoardAppDetail.tsx
client/src/components/BoardAppDetailsModal.tsx
client/src/components/BoardDetail.tsx
server/models/Listing.ts

- Modularizes BoardAppDetail and BoardAppDescription
- Allows for inline editing of both components

In modal editing

---

client/src/components/AppsColumn.tsx
client/src/layouts/AppsLayout.tsx
client/src/pages/AppsBoardPage.tsx

- Adds search input to filter apps on apps board

Board search apps

---

client/src/components/BoardAppComp.tsx
client/src/components/BoardAppCompensation.tsx
client/src/components/BoardAppDescription.tsx
client/src/components/BoardAppDetail.tsx
client/src/components/BoardAppDetailsModal.tsx
client/src/components/BoardAppStatus.tsx
client/src/utils/quillModules.ts

This PR: 
- updates UI for application details modal component

Application details modal UI

---

client/src/components/AppItem.tsx
client/src/components/AppsColumn.tsx
client/src/components/BoardAppShareSubmenu.tsx
client/src/index.css
client/src/pages/AppsBoardPage.tsx
client/tailwind.config.js

This PR:
- adds shadow variable for light and dark themes
- adds a shadow to sub-modals in the app detials
- adds shadow to application cards on kanban
- makes the title for kanban columns "fixed" (video below)
- makes "add column" button and column "fixed" (video below)
https://github.com/SVG-Productions/teamUpp/assets/100656411/6f9e304d-e79e-46d0-9a36-5a1dc0cfed29

Board app details submodal UI

---

client/src/components/RemoveApplicationModal.tsx
client/src/pages/ListingPage.tsx

- Creates new modal dedicated to removing team access from an application

Remove app from team modal

---

client/src/App.tsx
client/src/components/Pagination.tsx
client/src/layouts/AppsLayout.tsx
client/src/pages/AppsBoardPage.tsx
client/src/pages/AppsListPage.tsx

This PR: 
- adds the UI/page for the applications list view

Add applications list page (Front end)

---

client/src/App.tsx
client/src/layouts/AppsLayout.tsx
client/src/pages/AppsListPage.tsx
server/controllers/usersController.ts
server/models/User.ts

This PR: 
- adds server-side sort functionality to the AppsListPage
- add params to apps layout loader
- add conditionals to favorites and application Model calls in user controller
- and add sort to get Applications model

Applications list page sort query

---

client/src/App.tsx
client/src/layouts/AppsLayout.tsx
client/src/pages/AppsListPage.tsx
server/models/User.ts

This PR:
- adds pagination queries to the ApplicationsListPage
- updates queries for getUserApplications in User model
- removes console.log
- fixes misnamed loaders in browser router
- tests functionality of all applications pages (new loaders)

Applications list page pagination

---

client/src/components/SearchInput.tsx
client/src/pages/AppsListPage.tsx
server/models/User.ts

Please review and merge first: [PR341](https://github.com/SVG-Productions/teamUpp/pull/341)
This PR: 
- makes UI changes to SearchInput component (to match search for application board and list)
- adds SeachInput component to AppsListPage
- adds query to getUserApplications and getUserFavorites in User model

Applications list search query

---

client/src/App.tsx
client/src/components/SearchInput.tsx
client/src/layouts/AppsLayout.tsx
client/src/pages/AppsListPage.tsx
server/models/User.ts

Please review and merge these PRs first: [PR341](https://github.com/SVG-Productions/teamUpp/pull/341) [PR342](https://github.com/SVG-Productions/teamUpp/pull/342)
This PR: 
- adds filter query to AppsListPage and User model

Filter applications by status query

---

client/src/pages/AppsBoardPage.tsx

This PR:
- ensures app status is saved as lowercase to make sorting of application status more consistent

add lowercase app status to db for better status sorting

---

client/src/pages/AppsBoardPage.tsx
server/migrations/20230829215658_add_listing_accepted_column.js
server/models/User.ts
server/seeds/data/listings.js

This PR: 
- adds migration to add "accepted" column to listings table
- updates data for listing seed files
- adds logic to AppsBoardPage to update listing's accepted property
- updates query for accepted count for getUserInsights in User model

Update accepted listing query

---

client/src/components/InsightsDoughnut.tsx
client/src/components/InsightsLineGraph.tsx
client/src/pages/AppsInsightPage.tsx
client/src/utils/formatLineGraphData.ts

This PR: 
- removes "hidden" attribute for doughnut chart in mobile view
- other minor changes to Doughnut and Line graphs
- adds state and UI for InsightsLineGraph
- adds logic to formatLineGraphData util to handle showing previous months

Line graph previous month history

---

client/src/components/InsightsLineGraph.tsx
server/models/User.ts

This PR removes selects from user insight model

Insights line graph hotfix

---

client/src/components/BoardAppDetailsModal.tsx
client/src/utils/formatLineGraphData.ts
client/type-definitions.d.ts
server/models/Listing.ts
server/models/User.ts

This PR removes the knex .pluck() command from models and adjusts frontend to access newly formatted data appropriately

Remove pluck from models
